// knowledge-bulk-gen v11 (v26.50 ai_daily_usage Logging) — v10-base + RPC-Log vor success-Return.
// 35 Topics gesamt: 4 Wave-13 (alpine_garden_plants, forest_garden_design, indoor_houseplants, urban_balcony_design).
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

// v29 (HL#19): Admin-Secret NICHT mehr hardcodiert (war im public Repo lesbar) — wird zur Laufzeit
// aus app_settings.knowledge_gen_secret gelesen (nur admin/service-role lesbar, nie im Repo).

async function getAnthropicKey(admin: any): Promise<string | null> {
  const fromEnv = Deno.env.get("ANTHROPIC_API_KEY");
  if (fromEnv) return fromEnv;
  const { data } = await admin.from("app_settings").select("value").eq("key", "global_anthropic_api_key").maybeSingle();
  return data?.value ?? null;
}

type SchemaCfg = { table: string; system: string; uniqKey?: string; compositeUniq?: string[]; mapper?: (e: any) => any; };

const SCHEMAS: Record<string, SchemaCfg> = {
  recipes: { table: "recipes", uniqKey: "slug", system: `Schweizer Wildkräuter-Rezepte. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "description":"<2 Sätze>", "ingredients":[{"name":"<text>","qty":"<text>"}], "steps":["<schritt>"], "prep_time_min":<int>, "difficulty":"easy|medium|hard", "servings":<int>, "category":"<text>", "season":"<text>", "emoji":"<emoji>", "warning": null, "species_refs":["<lat>"] }. KEINE Markdown.` },
  remedies: { table: "remedies", uniqKey: "slug", system: `Schweizer Heilmittel. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "ailment":"<text>", "preparation":"<text>", "dosage":"<text>", "contraindications":null, "ingredients":[{"name":"<text>","qty":"<text>"}], "evidence_level":"traditional|folk|clinical|strong_clinical", "warning":null }. KEINE Markdown.` },
  folk_lore: { table: "folk_lore", uniqKey: "slug", system: `Schweizer Mythen. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "region":"<text>", "era":"<Mittelalter|Neuzeit|Modern>", "body":"<2-3 Sätze>", "category":"myth|tradition|folk_belief|recipe_lore|medicinal_lore|ritual|symbolism|seasonal_custom" }. KEINE Markdown.` },
  garden_techniques: { table: "garden_techniques", uniqKey: "slug", system: `Permakultur-Techniken Schweiz. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "short_desc":"<1 Satz>", "body":"<3 Sätze>", "steps":["<schritt>"], "benefits":["<vorteil>"], "tools":["<werkzeug>"], "category":"<MUSS einer von: pest_control, propagation, soil, companion, mulching, pruning, permaculture, seasonal, planting, fertilizing>", "difficulty":"easy|medium|hard" }. KEINE Markdown.` },
  did_you_know_facts: { table: "did_you_know_facts", uniqKey: "title", system: `Überraschende Fakten Schweizer Pflanzen. JSON-Array nur. Schema: { "title":"<kurzer titel unique>", "body":"<1-2 Sätze>", "icon":"<emoji>", "category":"plants|fungi|trees|herbs|animals", "month":<1-12 or null>, "is_active":true }. KEINE Markdown.` },
  seasonal_tips: { table: "seasonal_tips", uniqKey: "tip_key", system: `Saisonale Tipps. JSON-Array nur. Schema: { "tip_key":"<unique>", "title":"<text>", "body":"<2 Sätze>", "icon":"<emoji>", "category":"foraging|garden|harvest|observation|planting", "months":[<1-12>], "priority":<1-10>, "active":true }. KEINE Markdown.` },
  daily_quizzes: { table: "daily_quizzes", uniqKey: "question", system: `Quiz Schweiz. JSON-Array nur. Schema: { "question":"<text>", "answers":["<a>","<b>","<c>","<d>"], "correct_idx":<0-3>, "explanation":"<text>", "category":"identification|toxicity|culinary|medicinal|habitat|season", "difficulty":"easy|medium|hard" }. KEINE Markdown.`, mapper: (e: any) => ({ question: e.question, options: { answers: e.answers, correct: e.correct_idx, explanation: e.explanation, difficulty: e.difficulty }, category: e.category, xp_reward: 10, is_active: true }) },
  achievements: { table: "achievements_catalog", uniqKey: "slug", system: `Achievements. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "description":"<1 Satz>", "emoji":"<emoji>", "condition": {"type":"scan_count|garden_plant_count|quiz_streak","target":<int>}, "rarity":"common|rare|epic|legendary", "xp_reward":<int> }. KEINE Markdown.` },
  plant_diseases: { table: "plant_diseases", uniqKey: "slug", system: `Pflanzenkrankheiten Schweiz. JSON-Array nur. Schema: { "slug":"<unique>", "name":"<text>", "scientific_name":"<text or null>", "category":"pilz|bakterium|virus|schaedling|mangel|umweltstress", "severity":"leicht|mittel|schwer", "symptoms_de":"<text>", "symptoms_visual":["<text>"], "affected_parts":["blatt|stamm|wurzel|frucht"], "affected_species_lat":["<lat>"], "treatment_organic":"<text>", "treatment_chemical":null, "prevention":"<text>", "spread_method":"<text>", "optimal_conditions":"<text>", "emoji":"<emoji>", "warning":null }. KEINE Markdown.` },
  pollinators: { table: "pollinators", uniqKey: "slug", system: `Bestäuber Schweiz. JSON-Array nur. Schema: { "slug":"<unique>", "name":"<text>", "scientific_name":"<text or null>", "category":"wildbiene|honigbiene|schmetterling|kaefer|fliege|vogel", "emoji":"<emoji>", "description":"<text>", "habitat":"<text>", "active_months":[<1-12>], "preferred_flowers":["<lat>"], "preferred_colors":["gelb|lila|weiss|rosa|blau"], "conservation_status":"haeufig|gefaehrdet|stark_gefaehrdet", "ecological_value":"kritisch|hoch|mittel|niedrig", "swiss_native":true }. KEINE Markdown.` },
  garden_tasks_catalog: { table: "garden_tasks_catalog", uniqKey: "slug", system: `Garten-Aufgaben. JSON-Array nur. Schema: { "slug":"<unique>", "task_type":"aussaat|pflanzung|ernte|schnitt|duengung|vorbereitung|beobachtung", "title":"<text>", "description":"<2 Sätze>", "month_start":<1-12>, "month_end":<1-12>, "applies_to":["<text>"], "difficulty":"easy|medium|hard", "duration_min":<int>, "tools_needed":["<text>"], "weather_constraints":"<text or null>", "emoji":"<emoji>", "importance":"kritisch|wichtig|optional" }. KEINE Markdown.` },
  plant_companion_matrix: { table: "plant_companion_matrix", compositeUniq: ["species_a_lat", "species_b_lat"], system: `Mischkultur. JSON-Array nur. Schema: { "species_a_lat":"<lat>", "species_b_lat":"<lat>", "relationship":"gut|neutral|schlecht|kritisch_schlecht", "reason":"<text>", "effect_on_a":"<text>", "effect_on_b":"<text>", "source":"<text>", "confidence":"high|medium|low" }. KEINE Markdown.` },
  swiss_climate_zones: { table: "swiss_climate_zones", uniqKey: "slug", system: `Klimazonen. JSON-Array nur. Schema: { "slug":"<unique>", "zone_code":"<H1-H7>", "name":"<text>", "altitude_min_m":<int>, "altitude_max_m":<int>, "avg_temp_year_c":<num>, "frost_free_days":<int>, "rain_mm_year":<int>, "growing_season_months":<int>, "characteristics":"<text>", "suitable_plants":["<text>"], "challenging_plants":["<text>"], "regions_examples":["<text>"], "emoji":"<emoji>" }. KEINE Markdown.` },
  garden_problems: { table: "garden_problems", uniqKey: "slug", system: `Garten-Probleme. JSON-Array nur. Schema: { "slug":"<unique>", "name":"<text>", "category":"schaedling|tier|wetter|boden|licht|wasser|nachbar|wildwuchs", "severity":"leicht|mittel|schwer|existenzgefährdend", "description":"<text>", "symptoms":["<text>"], "affected_plants":["<text>"], "prevention_methods":["<text>"], "solutions_organic":["<text>"], "solutions_mechanical":["<text>"], "when_call_pro":"<text>", "emoji":"<emoji>", "swiss_specific":<bool> }. KEINE Markdown.` },
  harvest_preservation: { table: "harvest_preservation", uniqKey: "slug", system: `Konservierung. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "method":"einfrieren|einlegen|trocknen|einkochen|fermentieren|milchsauer_einlegen|salzen|zucker_einlegen|oel_einlegen|dehydrieren|sirup|marmelade|gelee|chutney", "applies_to":["<text>"], "applies_to_categories":["fruechte|gemuese|kraeuter|wildpflanzen|pilze"], "preparation_steps":["<text>"], "equipment_needed":["<text>"], "shelf_life_days":<int>, "storage_conditions":"<text>", "flavor_notes":"<text>", "difficulty":"easy|medium|hard", "swiss_tradition":<bool>, "emoji":"<emoji>" }. KEINE Markdown.` },
  seed_starting_calendar: { table: "seed_starting_calendar", uniqKey: "slug", system: `Aussaat-Kalender. JSON-Array nur. Schema: { "slug":"<unique>", "species_lat":"<lat or null>", "species_name":"<de name>", "category":"gemuese|kraeuter|blumen|obst", "month_indoor_start":<1-12 or null>, "month_outdoor_start":<1-12 or null>, "month_transplant":<1-12 or null>, "month_harvest_start":<1-12>, "month_harvest_end":<1-12>, "germination_days":<int>, "growing_days_total":<int>, "seed_depth_cm":<num>, "seed_spacing_cm":<int>, "row_spacing_cm":<int>, "light_requirement":"volle_sonne|halbschatten|schatten|dunkelkeimer|lichtkeimer", "ideal_soil_temp_c":<num>, "notes":"<text>", "swiss_climate_zones":["H1|H2|H3|H4|H5|H6|H7"], "emoji":"<emoji>" }. KEINE Markdown.` },
  seasonal_highlights: { table: "seasonal_highlights", uniqKey: "highlight_key", system: `Highlights. JSON-Array nur. Schema: { "highlight_key":"<unique>", "title":"<text>", "subtitle":"<text or null>", "body":"<2-3 Sätze>", "icon":"<emoji>", "species_id":"<lat or null>", "months":[<1-12>], "priority":<1-10>, "active":true }. KEINE Markdown.` },
  plant_pests: { table: "plant_pests", uniqKey: "slug", system: `Schädlinge. JSON-Array nur. Schema: { "slug":"<unique>", "common_name_de":"<text>", "common_name_fr":"<text or null>", "common_name_it":"<text or null>", "scientific_name":"<text or null>", "category":"insekt|milbe|schnecke|nematode|pilz_uebertragen|virusvektor|wirbeltier|sonstiges", "size_mm":"<text>", "body_color":"<text>", "affected_parts":["<text>"], "symptoms":"<text>", "identification_tips":"<text>", "damage_severity":"gering|mittel|hoch|katastrophal", "active_season":["<text>"], "host_plants":["<text>"], "natural_enemies":["<text>"], "treatment_organic":["<text>"], "treatment_chemical":["<text>"], "prevention":["<text>"], "source":"AGFF Schweiz" }. KEINE Markdown.` },
  compost_recipes: { table: "compost_recipes", uniqKey: "slug", system: `Kompost. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "name_fr":"<text or null>", "name_it":"<text or null>", "method":"hot_pile|cold_pile|vermicompost|bokashi|sheet_mulch|trench|tumbler|indoor_small", "duration_weeks_min":<int>, "duration_weeks_max":<int>, "difficulty":"einfach|mittel|fortgeschritten", "space_needed_m2":<num>, "inputs_browns":["<text>"], "inputs_greens":["<text>"], "ratio_browns_greens":"<text>", "ideal_temperature_c":"<text>", "moisture_target":"<text>", "ph_target":"<text>", "output_quality":"<text>", "best_for_garden":"<text>", "seasonal_start":["<text>"], "description":"<text>", "source":"Bioterra Schweiz" }. KEINE Markdown.` },
  propagation_methods: { table: "propagation_methods", uniqKey: "slug", system: `Vermehrung. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "name_fr":"<text or null>", "name_it":"<text or null>", "method_type":"saatgut|steckling_kraut|steckling_holz|steckling_blatt|absenker|teilung|wurzelschnitt|veredelung|meristem", "difficulty":"einfach|mittel|fortgeschritten|experte", "success_rate_pct":<int>, "duration_weeks":"<text>", "best_season":["<text>"], "applicable_plants":["<text>"], "not_for_plants":["<text>"], "required_tools":["<text>"], "required_substrate":"<text>", "temperature_min_c":<int>, "temperature_max_c":<int>, "light_requirement":"<text>", "humidity_pct":"<text>", "common_mistakes":["<text>"], "tips":["<text>"], "description":"<text>", "source":"Pro Specie Rara" }. KEINE Markdown.` },
  soil_amendments: { table: "soil_amendments", uniqKey: "slug", system: `Boden. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "name_fr":"<text or null>", "name_it":"<text or null>", "category":"mineralisch|organisch|tierisch|pflanzlich|synthetisch|bio_aktivator", "ph_effect":"stark_senkend|senkend|neutral|erhoehend|stark_erhoehend", "n_pct":<num>, "p_pct":<num>, "k_pct":<num>, "ca_pct":<num>, "mg_pct":<num>, "best_for_soil":"<text>", "application_rate":"<text>", "application_timing":"<text>", "effect_duration":"<text>", "works_well_with":["<text>"], "do_not_combine":["<text>"], "swiss_availability":"<text>", "cost_chf_per_kg":"<text>", "description":"<text>", "warnings":"<text>", "source":"AGFF/Bioterra Schweiz" }. KEINE Markdown.` },
  pest_companion_plants: { table: "pest_companion_plants", uniqKey: "slug", system: `Schädlings-Abwehr. JSON-Array nur. Schema: { "slug":"<unique>", "plant_name_de":"<text>", "plant_species_lat":"<text or null>", "role":"repellent|trap_plant|beneficial_insect_host|fungicidal|nematocidal|allelopathic_positive", "effective_against":["<text>"], "attracts":["<text>"], "active_compounds":["<text>"], "planting_pattern":"<text>", "best_paired_with":["<text>"], "do_not_pair_with":["<text>"], "swiss_native":<bool>, "bloom_months":[<1-12>], "height_cm":<int>, "notes":"<text>", "source":"FiBL/Pro Specie Rara" }. KEINE Markdown.` },
  medicinal_plants_register: { table: "medicinal_plants_register", uniqKey: "slug", system: `Heilpflanzen. JSON-Array nur. Schema: { "slug":"<unique>", "common_name_de":"<text>", "scientific_name":"<text>", "family":"<text>", "swiss_native":<bool>, "protected_species":<bool>, "used_parts":["<text>"], "primary_compounds":["<text>"], "secondary_compounds":["<text>"], "traditional_uses":["<text>"], "evidence_based_uses":["<text>"], "evidence_level":"traditional|folk|preclinical|clinical_weak|clinical_strong", "preparation_methods":["<text>"], "dosage_general":"<text>", "contraindications":["<text>"], "drug_interactions":["<text>"], "toxicity_notes":"<text>", "best_harvest_month":[<1-12>], "best_harvest_part_timing":"<text>", "conservation_status":"<text>", "swiss_legal_status":"<text>", "cultivation_notes":"<text>", "source":"Verein für Heilpflanzen Schweiz" }. KEINE Markdown.` },
  fertilization_schedules: { table: "fertilization_schedules", uniqKey: "slug", system: `Düngepläne. JSON-Array nur. Schema: { "slug":"<unique>", "plant_species_lat":"<lat or null>", "plant_name_de":"<text>", "phase":"aussaat|jungpflanze|vor_bluete|bluete|fruchtansatz|haupt_wachstum|reife|herbst_pflege|winter_ruhe", "weeks_after_planting":"<text>", "fertilizer_type":"<text>", "fertilizer_organic":["<text>"], "fertilizer_mineral":["<text>"], "application_method":"streuen|einarbeiten|bewaessern|blatt_spruehen|wurzel_giessen|mulch", "dose_g_per_m2":"<text>", "dose_ml_per_l":"<text>", "frequency":"<text>", "npk_focus":"<text>", "warnings":"<text or null>", "organic_certified":<bool>, "source":"AGFF/Bioterra" }. KEINE Markdown.` },
  seed_saving_methods: { table: "seed_saving_methods", uniqKey: "slug", system: `Samen-Gewinnung. JSON-Array nur. Schema: { "slug":"<unique>", "plant_species_lat":"<lat or null>", "plant_name_de":"<text>", "pollination_type":"selbstbestaeubung|fremdbestaeubung_wind|fremdbestaeubung_insekt|beides", "isolation_distance_m":<int>, "seeds_per_plant":"<text>", "viability_years":<int>, "harvest_timing":"<text>", "fruit_ripeness_signs":["<text>"], "extraction_method":"trocken|nass_fermentation|klopfen|zerdruecken|siebten", "cleaning_steps":["<text>"], "drying_method":"<text>", "drying_days":"<text>", "storage_temp_c":"<text>", "storage_humidity_pct":"<text>", "storage_container":"<text>", "difficulty":"einfach|mittel|fortgeschritten|experte", "variety_stability":"sortenecht|f1_aufspaltend|varianz_moeglich|hybride", "cultural_significance":"<text>", "description":"<text>", "warnings":"<text>", "source":"Pro Specie Rara" }. KEINE Markdown.` },
  garden_layouts: { table: "garden_layouts", uniqKey: "slug", system: `Beet-Designs. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "layout_type":"hochbeet|reihen_beet|spiral|mandala|keyhole|square_foot|hugelkultur|no_dig|permakultur_zone|indoor_balkon", "size_m2":<num>, "ideal_dimensions":"<text>", "difficulty":"einfach|mittel|fortgeschritten|experte", "setup_time_hours":<int>, "best_for_climate":["<text>"], "sun_requirement":"<text>", "yield_estimate_kg":"<text>", "maintenance_hours_week":<int>, "materials_needed":["<text>"], "cost_chf":"<text>", "best_for_beginners":<bool>, "swiss_specific":<bool>, "description":"<text>", "pro_tips":["<text>"], "common_pitfalls":["<text>"], "source":"Bioterra/Permakultur Schweiz" }. KEINE Markdown.` },
  mushroom_register: { table: "mushroom_register", uniqKey: "slug", system: `Schweizer Pilze. JSON-Array nur. Schema: { "slug":"<unique>", "common_name_de":"<text>", "common_name_fr":"<text or null>", "common_name_it":"<text or null>", "scientific_name":"<text>", "family":"<text>", "edibility":"speisepilz|speisepilz_jung|bedingt_essbar|ungeniessbar|giftig|toedlich|psychoaktiv|unbekannt", "vapko_klasse":"1|2|3|4|5", "habitat":["<text>"], "symbiosis_partners":["<text>"], "cap_diameter_cm_min":<num>, "cap_diameter_cm_max":<num>, "cap_color":["<text>"], "cap_surface":"<text>", "gills_or_pores":"<text>", "gill_color":"<text>", "spore_color":"<text>", "stem_color":"<text>", "stem_height_cm":"<text>", "flesh_color":"<text>", "smell":"<text>", "taste":"<text>", "identifying_features":"<text>", "toxic_compounds":["<text>"], "symptoms_if_toxic":"<text>", "emergency_action":"<text>", "cooking_preparation":"<text>", "conservation_methods":["<text>"], "swiss_distribution":"<text>", "season_months":[<1-12>], "altitude_m_min":<int or null>, "altitude_m_max":<int or null>, "protected_status":"<text>", "cultural_notes":"<text>", "source":"VAPKO Schweiz" }. KEINE Markdown.` },
  traditional_garden_wisdom: { table: "traditional_garden_wisdom", uniqKey: "slug", system: `Bauernregeln. JSON-Array nur. Schema: { "slug":"<unique>", "saying":"<text>", "saying_de":"<text or null>", "saying_dialect":"<text or null>", "region":"<text>", "meaning":"<text>", "category":"wetter|aussaat|ernte|pflege|marktstag|mondkalender|schaedling|wachstum", "validity":"wissenschaftlich_bestaetigt|tendenziell_richtig|aberglaube_widerlegt|umstritten", "modern_take":"<text>", "applicable_months":[<1-12>], "source":"Schweizer Bauernregel-Sammlung" }. KEINE Markdown.` },
  water_features: { table: "water_features", uniqKey: "slug", system: `Wassergarten. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "scientific_name":"<text or null>", "feature_type":"teichpflanze_sumpf|teichpflanze_flachwasser|teichpflanze_tiefwasser|schwimmpflanze|unterwasserpflanze|teichrand_feucht|wassertier_einheimisch|teich_design", "water_depth_cm_min":<int or null>, "water_depth_cm_max":<int or null>, "light_requirement":"<text>", "hardiness_zone":"<text>", "bloom_months":[<1-12> or null], "flower_color":"<text or null>", "spreading_behavior":"horstig_stabil|horstig_langsam_wuechsig|laeufer_kontrollierbar|laeufer_invasiv|schwimmt_frei", "water_filtration":"<text>", "oxygenating":<bool>, "attracts_wildlife":["<text>"], "swiss_native":<bool>, "invasive_in_ch":<bool>, "cost_chf_each":"<text>", "cultivation_tips":"<text>", "source":"Pro Natura" }. KEINE Markdown.` },
  mushroom_recipes: { table: "mushroom_recipes", uniqKey: "slug", system: `Pilz-Rezepte. JSON-Array nur. Schema: { "slug":"<unique>", "title":"<text>", "description":"<text>", "primary_mushroom_slugs":["<slug>"], "servings":<int>, "prep_time_min":<int>, "cooking_time_min":<int>, "difficulty":"einfach|mittel|fortgeschritten", "ingredients":[{"name":"<text>","qty":"<text>"}], "steps":["<text>"], "cooking_method":"braten|schmoren|suppe|sosse|einlegen|trocknen|fermentieren|grillen", "alcohol_pairing":"<text>", "food_pairing":"<text>", "swiss_tradition":<bool>, "region":"<text>", "emoji":"<emoji>", "warning":"<text or null>", "source":"Schweizer Pilzkochbuch" }. KEINE Markdown.` },
  garden_birds_register: { table: "garden_birds_register", uniqKey: "slug", system: `Vögel. JSON-Array nur. Schema: { "slug":"<unique>", "common_name_de":"<text>", "common_name_fr":"<text or null>", "common_name_it":"<text or null>", "scientific_name":"<text>", "family":"<text>", "size_cm":"<text>", "weight_g":"<text>", "status_in_ch":"haeufig|regelmaessig|gelegentlich|selten|sehr_selten|wintergast|sommervogel|zugvogel", "food_preferences":["<text>"], "nesting_location":["<text>"], "preferred_plants":["<text>"], "birdhouse_type":"<text>", "feeder_seeds":["<text>"], "active_months":[<1-12>], "song_description":"<text>", "red_list_status":"<text>", "attracting_tips":["<text>"], "threats":["<text>"], "fun_fact":"<text>", "source":"BirdLife Schweiz" }. KEINE Markdown.` },
  alpine_garden_plants: { table: "alpine_garden_plants", uniqKey: "slug", system: `CH-Alpenpflanzen. JSON-Array nur. Schema: { "slug":"<unique>", "common_name_de":"<text>", "scientific_name":"<text>", "family":"<text>", "altitude_m_min":<int>, "altitude_m_max":<int>, "swiss_native":<bool>, "protected_species":<bool>, "red_list_status":"<text>", "habitat_type":"<text>", "exposition":"<text>", "soil_preference":"<text>", "ph_preference":"<text>", "water_need":"trocken|maessig|feucht|wechselfeucht", "hardiness_to_celsius":<int>, "bloom_months":[<1-12>], "flower_color":"<text>", "height_cm":<int>, "spread_cm":<int>, "garden_suitability":"<text>", "rock_garden_role":"<text>", "companion_plants":["<text>"], "cultivation_difficulty":"einfach|mittel|schwer|experten", "cultivation_notes":"<text>", "warnings":"<text>", "source":"Pro Natura/SAC" }. KEINE Markdown.` },
  forest_garden_design: { table: "forest_garden_design", uniqKey: "slug", system: `Permakultur-Wald. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "design_type":"7_schichten_klassik|obstwiese|beerenstrauch_etage|pilz_etage|wurzel_etage|wein_etage|agroforst_alleen|food_forest_zone|wildhecken_garten", "size_m2_min":<int>, "size_m2_max":<int>, "difficulty":"einfach|mittel|fortgeschritten|experten", "setup_years":<int>, "yield_year_min":<int>, "full_maturity_years":<int>, "layer_canopy":["<text>"], "layer_understory":["<text>"], "layer_shrubs":["<text>"], "layer_herbaceous":["<text>"], "layer_groundcover":["<text>"], "layer_rhizosphere":["<text>"], "layer_vertical":["<text>"], "layer_mushroom":["<text>"], "swiss_climate_zones":["H1|H2|H3|H4|H5|H6|H7"], "best_for_slope":"<text>", "water_management":"<text>", "maintenance_hours_year":<int>, "yield_estimate_kg_year":"<text>", "initial_cost_chf":"<text>", "beneficial_animals":["<text>"], "description":"<text>", "pro_tips":["<text>"], "common_pitfalls":["<text>"], "source":"Permakultur Schweiz" }. KEINE Markdown.` },
  indoor_houseplants: { table: "indoor_houseplants", uniqKey: "slug", system: `Zimmerpflanzen. JSON-Array nur. Schema: { "slug":"<unique>", "common_name_de":"<text>", "scientific_name":"<text>", "family":"<text>", "origin_region":"<text>", "light_requirement":"direkt_sonne|heller_standort|halbschatten|schatten|beleuchtung", "watering_frequency":"taeglich|mehrfach_woche|woechentlich|alle_2_wochen|sparsam|sehr_sparsam|nur_winter_pause", "humidity_pct_min":<int>, "humidity_pct_max":<int>, "temperature_c_min":<int>, "temperature_c_max":<int>, "growth_speed":"sehr_langsam|langsam|mittel|schnell|sehr_schnell", "mature_size_cm":"<text>", "difficulty":"einfach|mittel|fortgeschritten|experten", "toxic_to_pets":<bool>, "toxic_to_children":<bool>, "pet_warnings":["<text>"], "air_purifying":<bool>, "propagation_method":["<text>"], "fertilizer_schedule":"<text>", "repotting_frequency":"<text>", "common_problems":["<text>"], "pest_susceptibility":["<text>"], "preferred_pot_material":"<text>", "description":"<text>", "pro_tips":["<text>"], "source":"Verband Schweizer Floristen" }. KEINE Markdown.` },
  urban_balcony_design: { table: "urban_balcony_design", uniqKey: "slug", system: `CH-Stadt-Balkon-Designs. JSON-Array nur. Schema: { "slug":"<unique>", "name_de":"<text>", "balcony_size_m2_min":<num>, "balcony_size_m2_max":<num>, "orientation":"sued|suedwest|west|suedost|ost|nord|geschlossen_wintergarten", "difficulty":"einfach|mittel|fortgeschritten", "setup_time_hours":<int>, "total_cost_chf":"<text>", "container_count":<int>, "container_types":["<text>"], "watering_strategy":"<text>", "irrigation_options":["<text>"], "wind_protection":"<text>", "sun_protection":"<text>", "winter_strategy":"<text>", "yield_estimate":"<text>", "maintenance_min_week":<int>, "best_for_swiss_cities":["<text>"], "pet_friendly":<bool>, "child_friendly":<bool>, "pro_tips":["<text>"], "common_pitfalls":["<text>"], "source":"Bioterra Stadtgarten" }. KEINE Markdown.` },
};

function salvageJsonArray(raw: string): any[] {
  let cleaned = raw.replace(/^```(?:json)?\s*/, "").replace(/\s*```\s*$/, "").trim();
  const startIdx = cleaned.indexOf("[");
  if (startIdx === -1) return [];
  cleaned = cleaned.substring(startIdx);
  try { const arr = JSON.parse(cleaned); return Array.isArray(arr) ? arr : [arr]; } catch (_) {}
  const objs: any[] = [];
  let depth = 0, inStr = false, escape = false, objStart = -1;
  for (let i = 0; i < cleaned.length; i++) {
    const ch = cleaned[i];
    if (escape) { escape = false; continue; }
    if (ch === "\\") { escape = true; continue; }
    if (ch === '"') { inStr = !inStr; continue; }
    if (inStr) continue;
    if (ch === "{") { if (depth === 0) objStart = i; depth++; }
    else if (ch === "}") { depth--; if (depth === 0 && objStart !== -1) { try { objs.push(JSON.parse(cleaned.substring(objStart, i + 1))); } catch (_) {} objStart = -1; } }
  }
  return objs;
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return new Response("Method Not Allowed", { status: 405 });
  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const svcKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const admin = createClient(supabaseUrl, svcKey);
  // v29 (HL#19): Admin-Secret aus app_settings statt hardcoded (war im public Repo lesbar).
  const { data: _sec } = await admin.from("app_settings").select("value").eq("key", "knowledge_gen_secret").maybeSingle();
  const expectedSecret = _sec?.value || "";
  if (!expectedSecret || req.headers.get("X-Admin-Secret") !== expectedSecret) return new Response("Forbidden", { status: 403 });
  try {
    const apiKey = await getAnthropicKey(admin);
    if (!apiKey) return new Response(JSON.stringify({ error: "No Anthropic key" }), { status: 503, headers: { "Content-Type": "application/json" } });
    const { topic, count = 12, focus_topics, model = "claude-haiku-4-5-20251001" } = await req.json();
    const schema = SCHEMAS[topic];
    if (!schema) return new Response(JSON.stringify({ error: `Unknown topic. Available: ${Object.keys(SCHEMAS).join(", ")}` }), { status: 400, headers: { "Content-Type": "application/json" } });
    let existKeys = new Set<string>();
    if (schema.uniqKey) {
      const { data: existing } = await admin.from(schema.table).select(schema.uniqKey);
      existKeys = new Set((existing || []).map((r: any) => r[schema.uniqKey!]));
    } else if (schema.compositeUniq) {
      const { data: existing } = await admin.from(schema.table).select(schema.compositeUniq.join(","));
      existKeys = new Set((existing || []).map((r: any) => schema.compositeUniq!.map((k) => r[k]).join("||")));
    }
    const userMsg = `Generiere genau ${count} ${topic}-Einträge. Schweizer Kontext, Deutsch.${focus_topics ? " Fokus: " + focus_topics.join(", ") : ""} Antworte mit reinem JSON-Array.`;
    const anthropicRes = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" }, body: JSON.stringify({ model, max_tokens: 8000, system: schema.system, messages: [{ role: "user", content: userMsg }] }) });
    if (!anthropicRes.ok) { const errBody = await anthropicRes.text(); return new Response(JSON.stringify({ error: "Anthropic", status: anthropicRes.status, detail: errBody.slice(0, 500) }), { status: 502, headers: { "Content-Type": "application/json" } }); }
    const aiData = await anthropicRes.json();
    const rawText = aiData.content?.[0]?.text || "";
    const stopReason = aiData.stop_reason || "";
    const entries = salvageJsonArray(rawText);
    if (!entries.length) return new Response(JSON.stringify({ error: "JSON salvage produced 0 entries", stop_reason: stopReason, raw_preview: rawText.slice(0, 600) }), { status: 502, headers: { "Content-Type": "application/json" } });
    const mapped = schema.mapper ? entries.map(schema.mapper) : entries;
    const newEntries = mapped.filter((e: any) => { if (schema.uniqKey) return e[schema.uniqKey] && !existKeys.has(e[schema.uniqKey]); if (schema.compositeUniq) { const key = schema.compositeUniq.map((k) => e[k]).join("||"); return schema.compositeUniq.every((k) => e[k]) && !existKeys.has(key); } return true; });
    let inserted = 0; const errors: any[] = [];
    for (const row of newEntries) { const { error } = await admin.from(schema.table).insert(row); if (error) { if (errors.length < 5) errors.push({ row_preview: JSON.stringify(row).slice(0, 80), error: error.message }); } else inserted++; }
    const { count: total } = await admin.from(schema.table).select("*", { count: "exact", head: true });

    // v26.50: Log usage (fire-and-forget)
    try {
      await admin.rpc("fn_log_ai_usage", {
        p_edge_fn: "knowledge-bulk-gen",
        p_tokens_in: aiData?.usage?.input_tokens || 0,
        p_tokens_out: aiData?.usage?.output_tokens || 0,
        // v30.95: p_model MUSS mit. Ohne ihn laeuft fn_log_ai_usage in den
        // else-Zweig `v_cost := 0` — 111 echte Calls mit 471'430 Output-Token
        // waren dadurch mit 0.00 CHF gebucht und fn_finance_snapshot meldete
        // eine um Faktor ~7,5 zu optimistische Deckung.
        p_model: aiData?.model || model,
      });
    } catch (_) { /* nicht-blockierend */ }

    return new Response(JSON.stringify({ ok: errors.length === 0, topic, generated: entries.length, salvaged: stopReason !== "end_turn", stop_reason: stopReason, new_unique: newEntries.length, inserted, total_in_db: total, tokens: aiData.usage, errors }, null, 2), { status: 200, headers: { "Content-Type": "application/json" } });
  } catch (e) { return new Response(JSON.stringify({ error: String((e as any)?.message ?? e) }), { status: 500, headers: { "Content-Type": "application/json" } }); }
});
