-- v26.96 — Pflanzen-Doktor v2: Diagnose-Historie + Behandlungs-Tracker + 7-Tage-Follow-up
-- Applied via MCP apply_migration (project vowbiueikwrauuceilhc). This file mirrors the
-- live DB state for repo parity. Hard-Lesson #8: the LIVE diagnosis path already writes to
-- plant_doctor_history (the spec's proposed plant_diagnoses is an orphaned expert table) —
-- so we EXTEND plant_doctor_history additively rather than creating a parallel table.

-- ── 1. Extend plant_doctor_history (additive) ────────────────────────────────
ALTER TABLE public.plant_doctor_history
  ADD COLUMN IF NOT EXISTS species_name     text,
  ADD COLUMN IF NOT EXISTS status           text NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS followup_due_at  timestamptz,
  ADD COLUMN IF NOT EXISTS followup_result  text,
  ADD COLUMN IF NOT EXISTS updated_at       timestamptz NOT NULL DEFAULT now();

-- CHECK constraints via DO-block (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pdh_status_chk') THEN
    ALTER TABLE public.plant_doctor_history
      ADD CONSTRAINT pdh_status_chk
      CHECK (status IN ('open','treating','resolved','worsened','abandoned'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pdh_followup_result_chk') THEN
    ALTER TABLE public.plant_doctor_history
      ADD CONSTRAINT pdh_followup_result_chk
      CHECK (followup_result IS NULL OR followup_result IN ('better','same','worse','unknown'));
  END IF;
END $$;

-- Indexes for plant-timeline + follow-up-due scan
CREATE INDEX IF NOT EXISTS idx_pdh_user_plant_created
  ON public.plant_doctor_history (user_id, plant_local_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pdh_followup_due
  ON public.plant_doctor_history (followup_due_at)
  WHERE status IN ('open','treating') AND followup_at IS NULL;

-- ── 2. Behandlungs-Tracker: plant_treatment_steps ────────────────────────────
CREATE TABLE IF NOT EXISTS public.plant_treatment_steps (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnosis_id uuid NOT NULL REFERENCES public.plant_doctor_history(id) ON DELETE CASCADE,
  user_id      uuid NOT NULL,
  step_label   text NOT NULL,
  done_at      timestamptz NOT NULL DEFAULT now(),
  photo_url    text,
  notes        text
);

CREATE INDEX IF NOT EXISTS idx_pts_diagnosis ON public.plant_treatment_steps (diagnosis_id);

ALTER TABLE public.plant_treatment_steps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pts_own ON public.plant_treatment_steps;
CREATE POLICY pts_own ON public.plant_treatment_steps
  FOR ALL TO authenticated
  USING (user_id = (SELECT auth.uid()))
  WITH CHECK (user_id = (SELECT auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.plant_treatment_steps TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.plant_treatment_steps_id_seq TO authenticated;

-- ── 3. symptom_library (dynamic symptom-picker source, public read) ──────────
CREATE TABLE IF NOT EXISTS public.symptom_library (
  slug          text PRIMARY KEY,
  category      text NOT NULL,
  label_de      text NOT NULL,
  label_en      text,
  label_es      text,
  icon          text,
  sort_order    smallint DEFAULT 100,
  common_causes text[] DEFAULT '{}'::text[]
);

ALTER TABLE public.symptom_library ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS symptom_library_read ON public.symptom_library;
CREATE POLICY symptom_library_read ON public.symptom_library
  FOR SELECT TO anon, authenticated USING (true);

GRANT SELECT ON public.symptom_library TO anon, authenticated;

INSERT INTO public.symptom_library (slug, category, label_de, label_en, label_es, icon, sort_order, common_causes) VALUES
  ('yellow_leaves',    'blatt',     'Gelbe Blätter',            'Yellow leaves',      'Hojas amarillas',     '🟡', 10,  ARRAY['wassermangel','naehrstoffmangel','sonne_zu_viel']),
  ('brown_spots',      'blatt',     'Braune Flecken',           'Brown spots',        'Manchas marrones',    '🟤', 20,  ARRAY['pilz','sonnenbrand','wassermangel']),
  ('white_powder',     'blatt',     'Weisser Belag',            'White powder',       'Polvo blanco',        '⚪', 30,  ARRAY['mehltau','spinnmilben']),
  ('curling_leaves',   'blatt',     'Eingerollte Blätter',      'Curling leaves',     'Hojas enrolladas',    '🍃', 40,  ARRAY['blattlaus','virus','trockenstress']),
  ('wilting',          'allgemein', 'Welke / Hängende Blätter', 'Wilting / Drooping', 'Marchitez',           '😩', 50,  ARRAY['wassermangel','wurzelfaeule']),
  ('stunted_growth',   'wuchs',     'Wachstumsstillstand',      'Stunted growth',     'Crecimiento atrofiado','🐌', 60,  ARRAY['naehrstoffmangel','licht_zu_wenig','topf_zu_klein']),
  ('rotting_stem',     'stamm',     'Faulender Stamm',          'Rotting stem',       'Tallo podrido',       '🦠', 70,  ARRAY['wurzelfaeule','bakterien']),
  ('webbing',          'blatt',     'Spinnweben',               'Webbing',            'Telarañas',           '🕸', 80,  ARRAY['spinnmilben']),
  ('sticky_residue',   'blatt',     'Klebriger Belag',          'Sticky residue',     'Residuo pegajoso',    '🍯', 90,  ARRAY['blattlaus','schildlaus']),
  ('pest_visible',     'allgemein', 'Sichtbare Schädlinge',     'Visible pests',      'Plagas visibles',     '🐛', 100, ARRAY['blattlaus','schildlaus','thrips']),
  ('leaf_holes',       'blatt',     'Löcher in Blättern',       'Holes in leaves',    'Agujeros en hojas',   '🕳️', 110, ARRAY['raupen','kaefer','schnecken']),
  ('dropping_leaves',  'allgemein', 'Blattfall',                'Dropping leaves',    'Caída de hojas',      '🍂', 120, ARRAY['trockenstress','zugluft','ueberwaesserung']),
  ('discolored_veins', 'blatt',     'Verfärbte Blattadern',     'Discolored veins',   'Venas descoloridas',  '🍁', 130, ARRAY['naehrstoffmangel','virus']),
  ('mushy_roots',      'wurzel',    'Matschige Wurzeln',        'Mushy roots',        'Raíces blandas',      '💧', 140, ARRAY['wurzelfaeule','ueberwaesserung'])
ON CONFLICT (slug) DO NOTHING;

-- ── 4. RPCs ──────────────────────────────────────────────────────────────────

-- 4a. Diagnose-Timeline für eine Pflanze (own-only, INVOKER)
CREATE OR REPLACE FUNCTION public.fn_plant_diagnoses_for_plant(p_plant_id text)
  RETURNS TABLE(id uuid, diagnosed_at timestamptz, photo_url text, species_name text,
                ai_diagnosis jsonb, treatment_plan jsonb, status text,
                followup_at timestamptz, followup_result text, treatment_steps_count integer)
  LANGUAGE sql STABLE SET search_path TO 'public'
AS $function$
  SELECT d.id, d.created_at, d.photo_url, d.species_name, d.ai_diagnosis, d.treatment_plan,
    d.status, d.followup_at, d.followup_result,
    (SELECT count(*)::int FROM public.plant_treatment_steps t WHERE t.diagnosis_id = d.id)
  FROM public.plant_doctor_history d
  WHERE d.user_id = (SELECT auth.uid()) AND d.plant_local_id = p_plant_id
  ORDER BY d.created_at DESC;
$function$;

-- 4b. Fällige Follow-ups (own-only, INVOKER)
CREATE OR REPLACE FUNCTION public.fn_followup_due()
  RETURNS TABLE(id uuid, plant_id text, plant_name text, diagnosis_top text,
                diagnosed_at timestamptz, days_overdue integer)
  LANGUAGE sql STABLE SET search_path TO 'public'
AS $function$
  SELECT d.id, d.plant_local_id,
    COALESCE(NULLIF(d.species_name,''), d.ai_diagnosis->>'top', 'Pflanze'),
    d.ai_diagnosis->>'top',
    d.created_at,
    GREATEST(0, EXTRACT(day FROM now() - d.followup_due_at)::int)
  FROM public.plant_doctor_history d
  WHERE d.user_id = (SELECT auth.uid())
    AND d.status IN ('open','treating')
    AND d.followup_at IS NULL
    AND d.followup_due_at IS NOT NULL
    AND d.followup_due_at <= now()
  ORDER BY d.followup_due_at ASC;
$function$;

-- 4c. Follow-up absenden (DEFINER; mapped better→resolved / worse→worsened / else→treating)
CREATE OR REPLACE FUNCTION public.fn_followup_submit(p_diagnosis_id uuid, p_result text,
                                                     p_notes text DEFAULT NULL,
                                                     p_new_photo_url text DEFAULT NULL)
  RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_uid uuid := (SELECT auth.uid()); v_new_status text;
BEGIN
  IF v_uid IS NULL THEN RETURN false; END IF;
  IF p_result NOT IN ('better','same','worse','unknown') THEN RETURN false; END IF;
  v_new_status := CASE p_result WHEN 'better' THEN 'resolved' WHEN 'worse' THEN 'worsened' ELSE 'treating' END;
  UPDATE public.plant_doctor_history
    SET followup_at = now(), followup_result = p_result, status = v_new_status, updated_at = now()
    WHERE id = p_diagnosis_id AND user_id = v_uid;
  IF NOT FOUND THEN RETURN false; END IF;
  IF p_notes IS NOT NULL OR p_new_photo_url IS NOT NULL THEN
    INSERT INTO public.plant_treatment_steps (diagnosis_id, user_id, step_label, photo_url, notes)
    VALUES (p_diagnosis_id, v_uid, 'Follow-up: ' || p_result, p_new_photo_url, p_notes);
  END IF;
  RETURN true;
END $function$;

-- 4d. Behandlungs-Schritt hinzufügen (DEFINER; ownership-check, status open→treating)
CREATE OR REPLACE FUNCTION public.fn_treatment_step_add(p_diagnosis_id uuid, p_step_label text,
                                                        p_photo_url text DEFAULT NULL,
                                                        p_notes text DEFAULT NULL)
  RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_uid uuid := (SELECT auth.uid()); v_new_id bigint;
BEGIN
  IF v_uid IS NULL OR p_step_label IS NULL OR length(trim(p_step_label)) = 0 THEN RETURN NULL; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.plant_doctor_history WHERE id = p_diagnosis_id AND user_id = v_uid) THEN RETURN NULL; END IF;
  INSERT INTO public.plant_treatment_steps (diagnosis_id, user_id, step_label, photo_url, notes)
  VALUES (p_diagnosis_id, v_uid, left(p_step_label, 200), p_photo_url, p_notes)
  RETURNING id INTO v_new_id;
  UPDATE public.plant_doctor_history SET status = 'treating', updated_at = now()
    WHERE id = p_diagnosis_id AND user_id = v_uid AND status = 'open';
  RETURN v_new_id;
END $function$;

-- 4e. Behandlungs-Schritte einer Diagnose (own-only, INVOKER)
CREATE OR REPLACE FUNCTION public.fn_treatment_steps_for_diagnosis(p_diagnosis_id uuid)
  RETURNS TABLE(id bigint, step_label text, done_at timestamptz, photo_url text, notes text)
  LANGUAGE sql STABLE SET search_path TO 'public'
AS $function$
  SELECT t.id, t.step_label, t.done_at, t.photo_url, t.notes
  FROM public.plant_treatment_steps t
  WHERE t.user_id = (SELECT auth.uid()) AND t.diagnosis_id = p_diagnosis_id
  ORDER BY t.done_at ASC;
$function$;

-- Grants: anon revoked on mutating/own-only RPCs, authenticated allowed
REVOKE ALL ON FUNCTION public.fn_followup_submit(uuid, text, text, text) FROM anon;
REVOKE ALL ON FUNCTION public.fn_treatment_step_add(uuid, text, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.fn_plant_diagnoses_for_plant(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_followup_due() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_followup_submit(uuid, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_treatment_step_add(uuid, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_treatment_steps_for_diagnosis(uuid) TO authenticated;
