-- v29.57b — Bauernregel-Content-Ausbau (traditional_garden_wisdom). Backend-only (Content), KEIN App-
-- v-Bump (Frontend gsLoadTodaysWisdom/gsRenderWisdom rendert die Tabelle bereits, 12h-Cache).
-- Fokus: Winter-Monate waren dünn (Jan 3, Feb 4, Dez 3) → der Tages-Filter nach applicable_months
-- hatte kaum Auswahl. 16 authentische, dokumentierte Bauernregeln mit korrekter wissenschaftlicher
-- Einordnung (inkl. ehrlich als aberglaube_widerlegt/umstritten markierte — Mission: aufklären statt
-- Mythen verbreiten). Idempotent via NOT EXISTS auf slug. Nach Migration: 42→58 Regeln, alle Monate
-- 9-20 Einträge. validity-Enum: wissenschaftlich_bestaetigt/tendenziell_richtig/umstritten/aberglaube_widerlegt.
insert into public.traditional_garden_wisdom (slug, saying, saying_de, saying_dialect, region, meaning, category, validity, modern_take, applicable_months, source)
select v.slug, v.saying, v.saying_de, v.saying_dialect, 'Schweiz', v.meaning, v.category, v.validity, v.modern_take, v.months::int[], 'Bauernregeln CH / MeteoSchweiz'
from (values
  ('januar-warm-gott-erbarm','Januar warm, dass Gott erbarm!','Ein zu warmer Januar gilt als schlechtes Zeichen','Januar warm — Gott erbarm','Ein zu milder Januar stört die Winterruhe und lässt Schädlinge überleben.','wetter','tendenziell_richtig','Zu warme Januare schwächen die Frosthärte der Pflanzen und Schädlinge überwintern besser — klimabedingt zunehmend.','{1}'),
  ('januar-hell-sommer-heiss','Ist der Januar hell und weiss, wird der Sommer gerne heiss','Klarer, schneereicher Januar — heisser Sommer','Januar hell — Summer gschwell','Verbindet einen klaren Hochdruck-Januar mit einem heissen Sommer.','wetter','umstritten','Statistisch kaum belastbar — Wetter über ein halbes Jahr ist nicht vorhersagbar.','{1}'),
  ('lichtmess-klee-ostern-schnee','Lichtmess im Klee, Ostern im Schnee','Milder Februaranfang (2.2.) — kalter Frühlingsbeginn','Liechtmäss im Chlee, Oschtere im Schnee','Ein zu früher, milder Vegetationsstart wird oft von Spätfrösten abgelöst.','wetter','umstritten','Erfahrungsregel mit schwacher statistischer Basis; der Grundgedanke (Vorsicht vor Spätfrost) ist berechtigt.','{2,3}'),
  ('lichtmess-dachs','Sonnt sich der Dachs in der Lichtmesswoche, geht er auf vier Wochen wieder zu Loche','Sonniger 2. Februar — vier weitere Wochen Winter','Schynt d''Sunne a Liechtmäss, chunnt de Winter no einisch','Tier-Verhalten am 2.2. soll den weiteren Winterverlauf anzeigen (wie der Murmeltiertag).','wetter','aberglaube_widerlegt','Kein meteorologischer Zusammenhang — ein einzelner Tag sagt nichts über vier Wochen Wetter aus.','{2}'),
  ('februar-wasser-gift','Februarwasser ist Gift, Februarschnee ein Segen','Regen im Februar schadet, Schnee nützt','Februar-Wasser isch Gift','Schnee isoliert den Boden und schützt vor Kahlfrost; Regen wäscht Nährstoffe aus und vereist.','wachstum','tendenziell_richtig','Eine schützende Schneedecke ist für Wintersaaten tatsächlich günstiger als nasskalter Regen.','{2}'),
  ('dezember-kalt-korn','Dezember kalt mit Schnee, gibt Korn auf jeder Höh','Kalter, schneereicher Dezember — gute Kornernte','Dezember chalt mit Schnee — git Chorn uf jeder Höh','Eine geschlossene Schneedecke schützt die Wintersaat vor Kahlfrost.','wachstum','wissenschaftlich_bestaetigt','Belegt: Schnee isoliert; Wintergetreide übersteht strengen Frost unter Schnee deutlich besser.','{12}'),
  ('wintergewitter-kaelte','Donnert es im Winter, kommt Kälte hinterher','Wintergewitter kündigt einen Kälteeinbruch an','Donneret''s im Winter, chunnt d''Chälti','Wintergewitter entstehen an markanten Kaltfronten — dahinter folgt oft polare Kaltluft.','wetter','tendenziell_richtig','Plausibel: Gewitter im Winter zeigen eine kräftige Kaltfront an, der Kälte folgt.','{12,1,2}'),
  ('gruene-weihnacht-weisse-ostern','Grüne Weihnacht, weisse Ostern','Schneefreie Weihnacht — Schnee an Ostern','Grüeni Wiehnacht — wyssi Oschtere','Ein mildes Weihnachten soll ein kaltes Osterfest nach sich ziehen.','wetter','aberglaube_widerlegt','Statistisch nicht belegt — die beiden Termine hängen meteorologisch nicht zusammen.','{12,3,4}'),
  ('allerheiligen-winter-martini','Bringt Allerheiligen Winter, so bringt Martini Sommer','Kälte um den 1.11. — Milde um den 11.11.','Bringt Allerheilige Winter, bringt Martini Summer','Ein früher Kälteeinbruch Anfang November werde oft von einer milden Phase um Martini abgelöst.','wetter','umstritten','Anspielung auf den oft milden „Martini-Sommer" — als feste Regel aber unsicher.','{11}'),
  ('kathrein-tanz','Kathrein stellt den Tanz ein','Mit dem 25.11. beginnt die stille Zeit','Chatry stellt de Tanz ii','Markiert das Ende der Feste und der Gartensaison vor dem Advent.','pflege','tendenziell_richtig','Brauchtums-Regel: ein guter Merktag, um die letzten Gartenarbeiten abzuschliessen.','{11}'),
  ('andreas-schnee','Andreasschnee tut den Saaten weh','Schnee um den 30.11. schadet der Saat','Andreas-Schnee tuet de Saate weh','Sehr früher Schnee vor ausreichender Abhärtung kann jungen Saaten schaden.','wetter','umstritten','Der Kern stimmt (früher Nassschnee ist ungünstig), als Datums-Regel aber unsicher.','{11,12}'),
  ('michaeli-wind','Wie der Wind an Michaeli weht, er den ganzen Winter steht','Windrichtung am 29.9. zeige den Winterwind an','Wie de Wind a Michaeli weiht','Die vorherrschende Windrichtung Ende September soll den Winter prägen.','wetter','umstritten','Ein einzelner Tag bestimmt nicht die Winter-Strömung — bestenfalls grobe Tendenz.','{9,10}'),
  ('altweibersommer-trocken','Spinnt im Herbst die Spinne sehr, kommt ein langer Winter her','Viele Altweibersommer-Fäden — schöner, ruhiger Herbst','Altwybersummer — schöne Herbst','Fliegende Spinnenfäden treten bei stabilem Hochdruck (Altweibersommer) auf.','wetter','tendenziell_richtig','Der Altweibersommer ist eine echte stabile Hochdrucklage — die Fäden sind ihr Begleiter.','{9,10}'),
  ('morgenrot-abendrot','Morgenrot mit Regen droht, Abendrot — Schönwetterbot','Rotes Morgenlicht kündigt Regen an, rotes Abendlicht schönes Wetter','Morgerot — Räge droht; Abigrot — schön Wätter-Bot','Bei unserer West-Strömung zeigt Morgenrot heranziehende Feuchte, Abendrot trockene Luft im Westen.','wetter','wissenschaftlich_bestaetigt','Physikalisch fundiert: hängt mit Lichtstreuung und dem Zug der Westwind-Wettersysteme zusammen.','{1,2,3,4,5,6,7,8,9,10,11,12}'),
  ('morgentau-schoenwetter','Tau am Morgen — der Tag wird schön','Morgentau deutet auf einen schönen Tag','Tau am Morge — kei Sorge','Tau bildet sich in klaren, windstillen Nächten — typisch für Hochdruck.','wetter','wissenschaftlich_bestaetigt','Stimmt: kräftiger Morgentau setzt eine klare Nacht voraus, meist bei stabilem Hochdruck.','{1,2,3,4,5,6,7,8,9,10,11,12}'),
  ('kuehe-legen-regen','Wenn die Kühe sich legen, gibt es bald Regen','Liegende Kühe sollen Regen ankündigen','Wenn d''Chüeh ligged, git''s Räge','Aus dem Liegeverhalten von Kühen soll man Regen vorhersagen können.','wetter','aberglaube_widerlegt','Kühe legen sich zum Wiederkäuen unabhängig vom Wetter — kein belegter Zusammenhang.','{1,2,3,4,5,6,7,8,9,10,11,12}')
) as v(slug, saying, saying_de, saying_dialect, meaning, category, validity, modern_take, months)
where not exists (select 1 from public.traditional_garden_wisdom t where t.slug = v.slug);
