-- v30.00 (Backend) · Voll-Snapshot planting_materials (11 Zeilen). Idempotenter UPSERT.
insert into public.planting_materials (item_key,item_de,category,unit,price_chf_min,price_chf_max,qty_formula_hint,notes) values
('anbindeband','Kokos-/Anbindeband (Baumbindeband)','schutz','m','0.50','2.50','ca. 1–2 m je Anbindepunkt; Achterschlaufe Pfahl–Stamm, 1–2 Bindungen je Baum','Kokosstrick/Bindeband Rolle ~CHF 5–12; breites Gummi-/Gurtband teurer. Pro Laufmeter grob CHF 0.50–2.50.'),
('drainagekies','Drainage-Kies (Sack)','drainage','Sack 40l','5.00','12.00','dünne Drainschicht im Pflanzloch bei staunassem Boden; grob 10–30 l je Baum → meist <1 Sack','Kies/Splitt 8–16 mm im Sack ~CHF 5–10; lose ab Bauhof günstiger. Nur bei verdichtetem/nassem Boden nötig.'),
('giessrand-vlies','Giessrand / Baumscheibe-Vlies','mulch','Stk','3.00','10.00','1 je Baum; Giessrand aus Aushuberde formen oder Mulchvlies in Baumscheibengrösse zuschneiden','Mulchvlies/Pflanzscheibe ~CHF 3–10/Stk; Giessrand kann auch kostenlos aus Aushub geformt werden.'),
('hornspaene','Hornspäne / Pflanzdünger (kg)','duenger','kg','4.00','10.00','ca. 50–100 g pro m² Baumscheibe bzw. ins Pflanzloch; ~0.1–0.3 kg je Jungbaum','Hornspäne/organischer Langzeitdünger ~CHF 4–8/kg (Sack 2.5–5 kg). Landi/Hornbach CH.'),
('pflanzerde','Pflanzerde / Kompost (Sack 40 l)','substrat','Sack 40l','6.00','14.00','Pflanzloch-Volumen minus Wurzelballen; grob 40–120 l je Baum → 1–3 Säcke à 40 l','Pflanz-/Gartenerde, Kompost 40 l ~CHF 6–10; torffreie Qualitätserde bis ~CHF 14 (Landi/Coop Bau+Hobby/Hornbach CH).'),
('pflanzpfahl','Pflanzpfahl (Akazie / imprägniert)','pfahl','Stk','5.00','15.00','1–3 je Baum je nach Höhe/Wind (1 Pfahl Einzelbaum windgeschützt, 2–3 als Dreibock bei Hochstamm/exponiert)','Akazie 5×5 cm 125–150 cm ~CHF 5.50–6.50 (Landi); imprägnierte/Lärche-Pfähle Hornbach ~CHF 4–6. Dickere Hochstamm-Pfähle bis ~CHF 15.'),
('rindenmulch','Rindenmulch (Sack)','mulch','Sack 40l','5.00','13.00','Baumscheibe π·r²·0.07 m (≈7 cm Schicht) → Liter; r ~0.5–0.75 m → ~55–120 l → 1–3 Säcke à 40–60 l','Rindenmulch/Pinienrinde 40–60 l ~CHF 5–10; Pinienrinde dekorativ bis ~CHF 13 (Landi/Hornbach CH).'),
('verbissschutz','Verbissschutz-Manschette (Spirale / Drahthose Einzelschutz)','schutz','Stk','2.00','12.00','1 je Jungbaum/Stamm (Spirale für Rinde, Drahthose gegen Reh-/Hasenverbiss)','Kunststoff-Wuchshülle/Spirale ~CHF 2–5/Stk; verzinkte Drahthose/Einzelschutz ~CHF 6–12/Stk (Landi/Hornbach CH).'),
('werkzeug-pauschal','Pflanzset / Werkzeug-Pauschal (Spaten/Astschere)','werkzeug','Pauschal','0.00','120.00','einmalig, nicht je Baum; 0 wenn vorhanden, sonst Grundausstattung Spaten + Astschere + Giesskanne','Spaten ~CHF 25–50, Astschere/Gartenschere ~CHF 15–40, Giesskanne ~CHF 10–25. Nur falls noch nicht vorhanden.'),
('wildschutzzaun','Wildschutzzaun (Knotengitter, pro m)','zaun','m','4.00','12.00','Umfang der zu schützenden Fläche in m (Rechteck: 2·(L+B)); Pfosten alle ~3 m separat rechnen','Knotengitter/Wildzaun 1.2–1.6 m Höhe ~CHF 4–8/m Material; mit Pfosten/Montage gegen oberes Ende. CH Landi/Hornbach.'),
('wuehlmauskorb','Wühlmaus-Drahtkorb (Pflanzkorb)','schutz','Stk','3.00','12.00','1 je Baum/Ballen; Korbgrösse passend zum Wurzelballen wählen','Verzinkter Pflanzkorb je nach Grösse ~CHF 3–12/Stk. Schützt Wurzeln vor Schermaus/Wühlmaus.')
on conflict (item_key) do update set item_de=excluded.item_de, category=excluded.category, unit=excluded.unit, price_chf_min=excluded.price_chf_min, price_chf_max=excluded.price_chf_max, qty_formula_hint=excluded.qty_formula_hint, notes=excluded.notes;
