-- v30.07 · tree_planting_specs: lokalisierte Befruchtersorten (pollination_partners_fr/it/en/es)
alter table public.tree_planting_specs
  add column if not exists pollination_partners_fr text[],
  add column if not exists pollination_partners_it text[],
  add column if not exists pollination_partners_en text[],
  add column if not exists pollination_partners_es text[];

update public.tree_planting_specs set pollination_partners_fr='{"Castanea sativa ''Marrone''","Castanea sativa ''Bouche de Bétizac''","Castanea sativa, semis"}'::text[], pollination_partners_it='{"Castanea sativa ''Marrone''","Castanea sativa ''Bouche de Bétizac''","Castanea sativa, semenzale"}'::text[], pollination_partners_en='{"Castanea sativa ''Marrone''","Castanea sativa ''Bouche de Bétizac''","Castanea sativa, seedling"}'::text[], pollination_partners_es='{"Castanea sativa ''Marrone''","Castanea sativa ''Bouche de Bétizac''","Castanea sativa, plántula"}'::text[] where slug='castanea_sativa';
update public.tree_planting_specs set pollination_partners_fr='{"Corylus avellana ''Hallesche Riesennuss''","Corylus avellana ''Webbs Preisnuss''","Corylus maxima ''Rotblättrige Zellernuss''"}'::text[], pollination_partners_it='{"Corylus avellana ''Hallesche Riesennuss''","Corylus avellana ''Webbs Preisnuss''","Corylus maxima ''Rotblättrige Zellernuss''"}'::text[], pollination_partners_en='{"Corylus avellana ''Hallesche Riesennuss''","Corylus avellana ''Webbs Preisnuss''","Corylus maxima ''Rotblättrige Zellernuss''"}'::text[], pollination_partners_es='{"Corylus avellana ''Hallesche Riesennuss''","Corylus avellana ''Webbs Preisnuss''","Corylus maxima ''Rotblättrige Zellernuss''"}'::text[] where slug='corylus_avellana';
update public.tree_planting_specs set pollination_partners_fr='{"Ilex aquifolium (clone mâle, p. ex. ''Blue Prince'' / ''Heckenstar'')"}'::text[], pollination_partners_it='{"Ilex aquifolium (clone maschile, ad es. ''Blue Prince'' / ''Heckenstar'')"}'::text[], pollination_partners_en='{"Ilex aquifolium (male clone, e.g. ''Blue Prince'' / ''Heckenstar'')"}'::text[], pollination_partners_es='{"Ilex aquifolium (clon masculino, p. ej. ''Blue Prince'' / ''Heckenstar'')"}'::text[] where slug='ilex_aquifolium';
update public.tree_planting_specs set pollination_partners_fr='{"Juglans regia ''Geisenheim''","Juglans regia ''Franquette''","Juglans regia ''Mars''"}'::text[], pollination_partners_it='{"Juglans regia ''Geisenheim''","Juglans regia ''Franquette''","Juglans regia ''Mars''"}'::text[], pollination_partners_en='{"Juglans regia ''Geisenheim''","Juglans regia ''Franquette''","Juglans regia ''Mars''"}'::text[], pollination_partners_es='{"Juglans regia ''Geisenheim''","Juglans regia ''Franquette''","Juglans regia ''Mars''"}'::text[] where slug='juglans_regia';
update public.tree_planting_specs set pollination_partners_fr='{"Juniperus communis mâle à proximité (dioïque)"}'::text[], pollination_partners_it='{"Juniperus communis maschile nelle vicinanze (dioico)"}'::text[], pollination_partners_en='{"male Juniperus communis nearby (dioecious)"}'::text[], pollination_partners_es='{"Juniperus communis masculino cercano (dioico)"}'::text[] where slug='juniperus_communis';
update public.tree_planting_specs set pollination_partners_fr='{"Lonicera caerulea var. kamtschatica (autre variété, p. ex. ''Wojtek'' × ''Aurora'')"}'::text[], pollination_partners_it='{"Lonicera caerulea var. kamtschatica (altra varietà, ad es. ''Wojtek'' × ''Aurora'')"}'::text[], pollination_partners_en='{"Lonicera caerulea var. kamtschatica (other variety, e.g. ''Wojtek'' × ''Aurora'')"}'::text[], pollination_partners_es='{"Lonicera caerulea var. kamtschatica (otra variedad, p. ej. ''Wojtek'' × ''Aurora'')"}'::text[] where slug='lonicera_caerulea_var_kamtschatica';
update public.tree_planting_specs set pollination_partners_fr='{"Malus domestica (autre variété)","Malus (pommier d''ornement)"}'::text[], pollination_partners_it='{"Malus domestica (altra varietà)","Malus (melo ornamentale)"}'::text[], pollination_partners_en='{"Malus domestica (other variety)","Malus (crabapple)"}'::text[], pollination_partners_es='{"Malus domestica (otra variedad)","Malus (manzano ornamental)"}'::text[] where slug='malus_domestica';
update public.tree_planting_specs set pollination_partners_fr='{"Prunus armeniaca (autre variété)"}'::text[], pollination_partners_it='{"Prunus armeniaca (altra varietà)"}'::text[], pollination_partners_en='{"Prunus armeniaca (other variety)"}'::text[], pollination_partners_es='{"Prunus armeniaca (otra variedad)"}'::text[] where slug='prunus_armeniaca';
update public.tree_planting_specs set pollination_partners_fr='{"Prunus avium (autre variété)","Prunus cerasus"}'::text[], pollination_partners_it='{"Prunus avium (altra varietà)","Prunus cerasus"}'::text[], pollination_partners_en='{"Prunus avium (other variety)","Prunus cerasus"}'::text[], pollination_partners_es='{"Prunus avium (otra variedad)","Prunus cerasus"}'::text[] where slug='prunus_avium';
update public.tree_planting_specs set pollination_partners_fr='{"Prunus domestica (autre variété)"}'::text[], pollination_partners_it='{"Prunus domestica (altra varietà)"}'::text[], pollination_partners_en='{"Prunus domestica (other variety)"}'::text[], pollination_partners_es='{"Prunus domestica (otra variedad)"}'::text[] where slug='prunus_domestica_subsp_domestica';
update public.tree_planting_specs set pollination_partners_fr='{"Prunus domestica (autre variété)"}'::text[], pollination_partners_it='{"Prunus domestica (altra varietà)"}'::text[], pollination_partners_en='{"Prunus domestica (other variety)"}'::text[], pollination_partners_es='{"Prunus domestica (otra variedad)"}'::text[] where slug='prunus_domestica_subsp_syriaca';
update public.tree_planting_specs set pollination_partners_fr='{"Pyrus communis (autre variété)"}'::text[], pollination_partners_it='{"Pyrus communis (altra varietà)"}'::text[], pollination_partners_en='{"Pyrus communis (other variety)"}'::text[], pollination_partners_es='{"Pyrus communis (otra variedad)"}'::text[] where slug='pyrus_communis';
update public.tree_planting_specs set pollination_partners_fr='{"dioïque - des plantes mâles et femelles sont nécessaires pour les graines ; pour la valeur florale/pour les insectes, un seul exemplaire suffit"}'::text[], pollination_partners_it='{"dioico - piante maschili e femminili sono necessarie per i semi; per il valore floreale/per gli insetti basta un solo esemplare"}'::text[], pollination_partners_en='{"dioecious - male and female plants needed for seeds; for flower/insect value a single specimen suffices"}'::text[], pollination_partners_es='{"dioico - se necesitan plantas masculinas y femeninas para las semillas; para el valor floral/para los insectos basta un solo ejemplar"}'::text[] where slug='salix_caprea';
update public.tree_planting_specs set pollination_partners_fr='{"Vaccinium corymbosum (autre variété pour un meilleur rendement)"}'::text[], pollination_partners_it='{"Vaccinium corymbosum (altra varietà per una migliore resa)"}'::text[], pollination_partners_en='{"Vaccinium corymbosum (other variety for better yield)"}'::text[], pollination_partners_es='{"Vaccinium corymbosum (otra variedad para mejor rendimiento)"}'::text[] where slug='vaccinium_corymbosum';
